### ISSUE TITLE
Error compiling tests using boost 1.70 from conda

### ISSUE THREAD

**Issue by IKN1** [cosmo-epfl/librascal#105]
When attempting to build the librascal tests, a compilation error occurs on test_adapter_filter.cc.o

    [ 25%] Building CXX object CMakeFiles/main_test_suite.dir/tests/test_adaptor_filter.cc.o
    /opt/applications/librascal/librascal/tests/test_adaptor_filter.cc:70:35: error: expected constructor, destructor, or type conversion before ‘(’ token
       BOOST_FIXTURE_TEST_CASE_TEMPLATE(constructor_test, Fix, Fixtures, Fix) {}
                                       ^
    /opt/applications/librascal/librascal/tests/test_adaptor_filter.cc:80:35: error: expected constructor, destructor, or type conversion before ‘(’ token
       BOOST_FIXTURE_TEST_CASE_TEMPLATE(filter_1_test, Fix, FixturesMax1, Fix) {
                                       ^
    /opt/applications/librascal/librascal/tests/test_adaptor_filter.cc:119:35: error: expected constructor, destructor, or type conversion before ‘(’ token
       BOOST_FIXTURE_TEST_CASE_TEMPLATE(filter_2_test, Fix, FixturesMax2, Fix) {
                                       ^
    make[2]: *** [CMakeFiles/main_test_suite.dir/build.make:87: 
    CMakeFiles/main_test_suite.dir/tests/test_adaptor_filter.cc.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:202: CMakeFiles/main_test_suite.dir/all] Error 2
    make: *** [Makefile:139: all] Error 2

I am trying to build on Red Hat 6 using devtoolset-7 and anaconda 5.0.1 (Python 3.6.3). Boost 1.70 is installed in anaconda, and the cmake script finds it and seems to be OK with it:

    $ cmake3 -DBUILD_TESTS=ON -DENABLE_DOC=ON ..
    -- The C compiler identification is GNU 7.3.1
    -- The CXX compiler identification is GNU 7.3.1
    -- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
    -- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
    -- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Build type is: Release
    -- Downloading Eigen3
    -- Eigen3 3.3.4
    -- The optional cpplint parser has not been found. For more information see https://pypi.python.org/pypi/cpplint
    -- The optional clang-format auto formatter has not been found. For more information see https://clang.llvm.org/docs/ClangFormat.html
    -- autopep8 auto formatter: /opt/applications/anaconda3/bin/autopep8
    -- Found PythonInterp: /opt/applications/anaconda3/bin/python3 (found suitable version "3.6.3", minimum required is "3")
    -- Found PythonLibs: /opt/applications/anaconda3/lib/libpython3.6m.so
    -- Downloading pybind11
    -- pybind11 v2.2.2
    -- Installation ROOT: /opt/applications/anaconda3
    -- Found Boost 1.70.0 at /opt/applications/anaconda3/lib/cmake/Boost-1.70.0
    --   Requested configuration: QUIET REQUIRED COMPONENTS unit_test_framework
    -- Found boost_headers 1.70.0 at /opt/applications/anaconda3/lib/cmake/boost_headers-1.70.0
    -- Found boost_unit_test_framework 1.70.0 at 
    /opt/applications/anaconda3/lib/cmake/boost_unit_test_framework-1.70.0
    --   libboost_unit_test_framework.so.1.70.0
    -- Adding boost_unit_test_framework dependencies: headers
    Boost  found.
    Found Boost components:
       unit_test_framework
    -- Found Sphinx: /opt/applications/anaconda3/bin/sphinx-build
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /opt/applications/librascal/librascal/build

librascal.so itself seems to build fine and I only get an error on the tests. If I don't include the ```-DBUILD_TESTS=ON``` flag for ```cmake3```, then ```make``` runs fine, even for the documentation.

**Comment by mastricker** [comment]
Hi Ian,

thank you very much for your interest in our project and pointing out the issue!
We are currently (still) under heavy development and `librascal` is not yet officially released. So a hearty welcome as an alpha-tester.

We have tested `librascal`up until boost 1.67.0, but not in conjunction with conda and 1.70. We are at least not testing it explicitly in the unit tests. There might be a person using it on the team but without issues and probably an older version.

We will have a look into the issue with boost and try to fix it as soon as possible.
In case you find a possible solution, feel free to share.

**Comment by felixmusil** [comment]
I tried to reproduce your error on my ubuntu machine and I can't but I do get an error which might be tied to how the conda version of boost (on conda-forge) has been compiled (https://stackoverflow.com/questions/30668560/boost-unit-test-link-error-abi-mismatch).  
It used to work a few month ago though... I will try to see if I can fix this otherwise I will drop this suggestion from BOOST.md

**Comment by felixmusil** [comment]
This issue can be reopened if the problem persist.
