### ISSUE TITLE
CMake script appears to ignore BOOST_ROOT and Boost_NO_SYSTEM_PATHS variables

### ISSUE THREAD

**Issue by IKN1** [cosmo-epfl/librascal#106]
In trying to workaround issue #105 I compiled boost from source according to the instructions in the [BOOST.md](https://github.com/cosmo-epfl/librascal/blob/master/BOOST.md) guide. As part of the instructions, I set the ```BOOST_ROOT``` and ```Boost_NO_SYSTEM_PATHS``` environment variables and then ran the ```cmake3```. In doing this, though, the CMake script seemed to still look for boost in my python installation (anaconda 5.0.1, python 3.6.3), which is what I was trying to avoid. Here is how I setup my environment and then the results of ```cmake3```

    $ ls /opt/applications/installers/boost/boost_1_67_0/boost_root/
    include  lib
    $ ls -l  /opt/applications/installers/boost/boost_1_67_0/boost_root/lib/
    total 6112
    -rw-rw-r-- 1 ppuser2 ppuser2  142498 Jul 16 13:14 libboost_chrono.a
    lrwxrwxrwx 1 ppuser2 ppuser2      25 Jul 16 13:13 libboost_chrono.so -> libboost_chrono.so.1.67.0
    -rwxrwxr-x 1 ppuser2 ppuser2   41448 Jul 16 13:13 libboost_chrono.so.1.67.0
    -rw-rw-r-- 1 ppuser2 ppuser2  151542 Jul 16 13:18 libboost_prg_exec_monitor.a
    lrwxrwxrwx 1 ppuser2 ppuser2      35 Jul 16 13:13 libboost_prg_exec_monitor.so -> libboost_prg_exec_monitor.so.1.67.0
    -rwxrwxr-x 1 ppuser2 ppuser2   90376 Jul 16 13:13 libboost_prg_exec_monitor.so.1.67.0
    -rw-rw-r-- 1 ppuser2 ppuser2   68472 Jul 16 13:14 libboost_system.a
    lrwxrwxrwx 1 ppuser2 ppuser2      25 Jul 16 13:13 libboost_system.so -> libboost_system.so.1.67.0
    -rwxrwxr-x 1 ppuser2 ppuser2  148904 Jul 16 13:13 libboost_system.so.1.67.0
    -rw-rw-r-- 1 ppuser2 ppuser2 2264840 Jul 16 13:16 libboost_test_exec_monitor.a
    -rw-rw-r-- 1 ppuser2 ppuser2   31344 Jul 16 13:14 libboost_timer.a
    lrwxrwxrwx 1 ppuser2 ppuser2      24 Jul 16 13:13 libboost_timer.so -> libboost_timer.so.1.67.0
    -rwxrwxr-x 1 ppuser2 ppuser2   30344 Jul 16 13:13 libboost_timer.so.1.67.0
    -rw-rw-r-- 1 ppuser2 ppuser2 2241950 Jul 16 13:18 libboost_unit_test_framework.a
    lrwxrwxrwx 1 ppuser2 ppuser2      38 Jul 16 13:14 libboost_unit_test_framework.so -> libboost_unit_test_framework.so.1.67.0
    -rwxrwxr-x 1 ppuser2 ppuser2 1026168 Jul 16 13:14 libboost_unit_test_framework.so.1.67.0 
    $
    $
    $
    $ export Boost_NO_SYSTEM_PATHS=ON
    $ export BOOST_ROOT=/opt/applications/installers/boost/boost_1_67_0/boost_root
    $ echo $BOOST_ROOT
    /opt/applications/installers/boost/boost_1_67_0/boost_root
    $
    $
    $
    $ cmake3 -DBUILD_TESTS=ON -DENABLE_DOC=ON  ..
    -- The C compiler identification is GNU 7.3.1
    -- The CXX compiler identification is GNU 7.3.1
    -- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc
    -- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++
    -- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Build type is: Release
    -- Downloading Eigen3
    -- Eigen3 3.3.4
    -- The optional cpplint parser has not been found. For more information see https://pypi.python.org/pypi/cpplint
    -- The optional clang-format auto formatter has not been found. For more information see https://clang.llvm.org/docs/ClangFormat.html
    -- autopep8 auto formatter: /opt/applications/anaconda3/bin/autopep8
    -- Found PythonInterp: /opt/applications/anaconda3/bin/python3 (found suitable version "3.6.3", minimum required is "3")
    -- Found PythonLibs: /opt/applications/anaconda3/lib/libpython3.6m.so
    -- Downloading pybind11
    -- pybind11 v2.2.2
    -- Installation ROOT: /opt/applications/anaconda3
    -- Found Boost 1.70.0 at /opt/applications/anaconda3/lib/cmake/Boost-1.70.0
    --   Requested configuration: QUIET REQUIRED COMPONENTS unit_test_framework
    -- Found boost_headers 1.70.0 at /opt/applications/anaconda3/lib/cmake/boost_headers-1.70.0
    -- Found boost_unit_test_framework 1.70.0 at /opt/applications/anaconda3/lib/cmake/boost_unit_test_framework-1.70.0
    --   libboost_unit_test_framework.so.1.70.0
    -- Adding boost_unit_test_framework dependencies: headers
    Boost  found.
    Found Boost components:
       unit_test_framework
    -- Found Sphinx: /opt/applications/anaconda3/bin/sphinx-build
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /opt/applications/librascal/librascal/build

I believe I followed the instructions in BOOST.md, so I'm wondering if there's a problem with the instructions or if there's an issue in the CMake script?

**Comment by felixmusil** [comment]
I am not an expert with cmake so when I run into such issues I run
```
shopt -s extglob
    rm -fr -- !(external|third-party)
```
in the build folder to be sure the cmake variables are reset. There might be a cleaner way but I only found this reference stating the contrary https://stackoverflow.com/questions/9680420/looking-for-a-cmake-clean-command-to-clear-up-cmake-output.

Then you can start again t build the library and it should not be confused anymore.

**Comment by felixmusil** [comment]
to have a look/modify these variables I use ccmake. The boost related variables are in the advanced mode.

**Comment by max-veit** [comment]
They're stored in `build/CMakeCache.txt`

**Comment by felixmusil** [comment]
is it still an issue ?
