### ISSUE TITLE
Gradient implementation does not correctly handle periodic images

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#115]
In a periodic system with the environment cutoff larger than one of the cell dimensions (and _not_ using the minimum-image convention), the gradient of a property with respect to the motion of some centre must also account for the motion of its periodic images within that cutoff. This is not currently done, as all atoms in the neighbourhood of a centre are summed over in the gradient computation. As the drawing below illustrates, the correct gradient simply omits the contributions from those neighbours that are periodic images of the central atom, as the distance between those images does not change with motion of the central atom.

![IMG_2526](https://user-images.githubusercontent.com/719666/63877400-daeab300-c9c7-11e9-81a9-849157ab3672.JPG)

The fix is simple: We just need a test for each atom in the neighbourhood to see if it's an image of the central atom and, if so, skip its "contribution" to the gradient.

**Comment by ceriottm** [comment]
Well-spotted! Doesn't this show up in finite-difference tests of the
gradient?

**Comment by max-veit** [comment]
Yes! But I initially ignored it as an artefact and disabled PBCs for the gradient tests: https://github.com/cosmo-epfl/librascal/blob/0fd95f5406be0674be7fde7dc182c5656361a70c/tests/test_representation_manager.cc#L244-L246

If there's a lesson here, it's that we should have listened to what the gradient test was trying to tell us.

**Comment by felixmusil** [comment]
This issue will be solved easily in the feat/adaptor_center_contribution branch.

**Comment by max-veit** [comment]
How exactly? What does that branch do again? It's not related to #104, is it? Because I thought that issue was for something we decided was no longer needed. We really shouldn't iterate over center pairs, because they're always handled differently -- and you could argue that the behaviour we're seeing here is in fact an artefact of iterating over the center pairs, only in different periodic images, and that's something we should be able to explicitly switch off.

**Comment by felixmusil** [comment]
> How exactly?

very simple: atom_i has a tag and you can get the tag associated to atom_j with get_atom_j() and then check if both are the same -> then it is an image of the center atom. get_atom_j is an addition of this branch.
There is no clear pattern in the way we store the neighbors that would allow to avoid the if statement I think.

> I thought that issue was for something we decided was no longer needed.

You might have misunderstood. This feature is essential in the coefficients building with gradients and in the kernel building with gradients.

> you could argue that the behaviour we're seeing here is in fact an artefact of iterating over the center pairs, only in different periodic images

that is true for gradients but we still want these contributions for the representation. Without changing too many things we could create another custom iterator like .with_ghost() that would encapsulate the iteration and the if statement to check if it is actually an image of the center. Might be better than doing it by hand in several places ?

**Comment by max-veit** [comment]
Status update: We've implemented something that should _in theory_ fix the issue, but in practice it doesn't (possibly due to interaction with #143). More to come soon.
