### ISSUE TITLE
Error importing librascal when compiled with gcc9

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#127]
Utterly puzzling and frustrating, probably related to [this upstream pybind11 issue](https://github.com/pybind/pybind11/issues/994) which they currently seem unwilling or unable to investigate.

Steps to reproduce (on the current `master`):
- Make a clean conda environment with the necessary packages (`conda list` 
[attached](https://github.com/cosmo-epfl/librascal/files/3647299/conda.list.txt))
- Install GCC 9.1.0
- Run `cmake`, let it install `pybind11` (error occurs with versions 2.2.2, 2.3.0 (rascal default), and 2.4.2 (latest stable)) (
[`CMakeCache.txt` attached](https://github.com/cosmo-epfl/librascal/files/3647397/CMakeCache.txt))

- Build everything with `make`
- Try to import a rascal representation from the build directory (though the exact same thing happens when running in another directory and adding `build/` to the python path):
```python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os; os.getcwd()
'/local/scratch/mveit/codes/librascal/build'
>>> from rascal.representations import SphericalInvariants
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/local/scratch/mveit/codes/librascal/build/rascal/representations/__init__.py", line 1, in <module>
    from .coulomb_matrix import SortedCoulombMatrix
  File "/local/scratch/mveit/codes/librascal/build/rascal/representations/coulomb_matrix.py", line 4, in <module>
    from ..neighbourlist import AtomsList
  File "/local/scratch/mveit/codes/librascal/build/rascal/neighbourlist/__init__.py", line 1, in <module>
    from .structure_manager import AtomsList, get_neighbourlist, convert_to_structure_list
  File "/local/scratch/mveit/codes/librascal/build/rascal/neighbourlist/structure_manager.py", line 1, in <module>
    from .base import (NeighbourList, NeighbourListFactory, is_valid_structure,
  File "/local/scratch/mveit/codes/librascal/build/rascal/neighbourlist/base.py", line 1, in <module>
    from ..lib import NeighbourList
  File "/local/scratch/mveit/codes/librascal/build/rascal/lib/__init__.py", line 1, in <module>
    from ._rascal import (NeighbourList, Models,
ImportError: generic_type: cannot initialize type "ClusterRef": an object with that name is already defined
>>> 
```
The error does not occur with GCC 7. Not sure if it's the mismatch in compiler versions between my Python interpreter and the compiled module, but that's the only thing I can think of right now.

**Comment by felixmusil** [comment]
I don't think it is gcc9 or gcc8 per se that are at fault but how they are compiled since these two version distributed on apt-get are fine on my machine.

**Comment by max-veit** [comment]
So what is there left to do? Compile gcc9 from scratch and see if that fixes things? Can you please check the configurations and make sure everything really is exactly the same?

**Comment by felixmusil** [comment]
I already checked for the 2 gcc versions from apt-get on ubuntu.

**Comment by Luthaf** [comment]
From your CMakeCache.txt, `CMAKE_CXX_COMPILER` is set to `/usr/bin/c++`. Are you sure this is GCC 9?

The way I usually force cmake to use a different compiler is with `CC=gcc-9 CXX=g++-9 cmake ..` (the right way™ to do this is actually `cmake -DCMAKE_CXX_COMPILER=/full/path/to/g++-9 -DCMAKE_C_COMPILER=/full/path/to/gcc-9 ..` but this is annoying to type ...)

**Comment by max-veit** [comment]
Hmm, I know that's the default (check your own configuration; I'll bet it's the same). But yes, both `/usr/bin/cc` and `/usr/bin/c++` point to gcc 9.1.0.

When I set it to use gcc 7, then of course I set those cmake variables (using `ccmake`, I'll admit, but should be the same either way, no?).

**Comment by Luthaf** [comment]
Locally I have:

```
 $ /usr/bin/cc --version
cc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
[...]
```

> using ccmake, I'll admit, but should be the same either way, no?

Not always, as you can only set compilers on the first run of cmake/ccmake, you can not change them.

**Comment by Luthaf** [comment]
I managed to reproduce the issue with GCC 9.2.1 on Fedora 30.

I tracked it down to `GetTypeNameHelper`  producing the same output when instantiated with `ClusterRefKey<Order, Layer>` with the same Order and different Layer values.

https://github.com/cosmo-epfl/librascal/blob/4ebb7dd77925caeee228e2e373535e440dddfb2f/src/rascal_utility.hh#L258

```
__PRETTY_FUNCTION__ => static const string rascal::internal::GetTypeNameHelper<T>::GetTypeName() [with T = rascal::ClusterRefKey<1, 0>; std::string = std::__cxx11::basic_string<char>]
GetTypeNameHelper => rascal::ClusterRef
GetTypeName => ClusterRef

__PRETTY_FUNCTION__ => static const string rascal::internal::GetTypeNameHelper<T>::GetTypeName() [with T = rascal::ClusterRefKey<1, 1>; std::string = std::__cxx11::basic_string<char>]
GetTypeNameHelper => rascal::ClusterRef
GetTypeName => ClusterRef
```

The code of `GetTypeNameHelper` mention not using RTTI and `type_name`, why is that required?

**Comment by felixmusil** [comment]
Thanks a lot for looking into it. I solve this issue in #147.
