### ISSUE TITLE
Atoms mask is effectively masking non-ghost/ghost and should be implemented like it

### ISSUE THREAD

**Issue by mastricker** [cosmo-epfl/librascal#180]
The current implementation of the masking functionality (n_atoms, n_centers, n_ghosts) is very confusing. I.e. it is buggy and not well defined.

I am calling this a bug, because the tests currently fail.

The suggestion is that masked/not masked atoms should be treated like ghost/non ghost atoms. Because that is effectively what it is: _only_ neighbours.

The issues that arise are connected to the correct sizing of Properties, especially when using them in conjunction with a calculator, where you only want to calculate and store data for center atoms.

I'll put it in the meeting minutes to talk about next week. Or maybe we solve it here.

Just to help organize the thoughts.

Definition upfront:
_Ghost_ atoms are atoms which are only neighbours, i.e. j-atoms. 
_Center_ atoms are atoms which are i-atoms and are intended to be _worked_ on.

The masking functionality effectively treats non-centers like ghosts in this definition.

- `get_size()` returns the number of centers
- `get_size_with_ghosts()` should return the number of centers + ghosts. 
- There is no other _size_ nor should there be.
- Sizing of properties of Order 1 should be to the return value of `get_size_with_ghosts()` as a default. For calculating representations, it should be possible to make it differently, to the number of `get_size()` - which are the centers.

**Comment by felixmusil** [comment]
> I am calling this a bug, because the tests currently fail.

what do you mean by that ? the functionality is in master since a month and the tests are passing there no ?

> Sizing of properties of Order 1 should be to the return value of get_size_with_ghosts() as a default. For calculating representations, it should be possible to make it differently, to the number of get_size() - which are the centers.

Is this related to the use of Property to store indices where you would like to have the size with the ghost  while it the number of center atom is expected when it comes to representations ?
I feel you would break the logic of the Property by sizing it with get_size_with_ghosts() but let's discuss this next meeting.

**Comment by mastricker** [comment]
> what do you mean by that ? the functionality is in master since a month and the tests are passing there don't they ?

The flag `consider_ghost_neighbours` is gone. Hence the logic is gone. Therefore the test do fail on this branch.

> Is this related to the use of Property to store indices where you would like to have the size with the ghost while it the number of center atom is expected when it comes to representations ?
> I feel you would break the logic of the Property by sizing it with get_size_with_ghosts() but let's discuss this next meeting.

If I get you right, yes. I suggest I change it to what I think should be the logic now and you can have a look. But also allowing for properties which are sized according the the number of centers which not masked (as in the ones you would want the calculation on, i.e. the return of `get_size`).

I mean we have a common understanding of what a ghost atom is now, if I am not mistaken, the definition I outlined above, right?
So in that definition the masked atoms of a structure (the ones which are not considered _centers_) should be called _ghosts_ now.

**Comment by max-veit** [comment]
FWIW, QUIP does have a definition of "centers to skip computing descriptors for" _separate_ from the definition of "ghost atoms" (periodic images). The former is decided by species keys, and the latter is just atoms outside the unit cell. I think it's useful to keep that distinction.

**Comment by mastricker** [comment]
This has been solved an merged.
