### ISSUE TITLE
Improve discoverability of benchmark tutorial

### ISSUE THREAD

**Issue by mastricker** [cosmo-epfl/librascal#202]
Benchmark tutorial is not easily findable. Make developer tutorial.

**Comment by agoscinski** [comment]
I put the `benchmark_tutorial.cc` now into the `docs/source/tutorials` is this good for everyone?

**Comment by Luthaf** [comment]
I think it should also be included in the online HTML documentation, so that all tutorials and dev docs are available from there.

**Comment by agoscinski** [comment]
It is also referenced in the `docs/source/dev_guide/benchmark_tutorial.rst`

**Comment by Luthaf** [comment]
Sounds good then!
