### ISSUE TITLE
SphericalInvariants gradient tries to access periodic images of a center

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#213]
(It shouldn't do this, as the periodic images don't contribute to the gradient.)

This is an after-effect of #179, as we added the neighbour exclusion to SphericalExpansion but not any of the representations _derived_ from it. This didn't cause any errors at the time, but certain corner cases can trigger memory errors during the tests -- for instance, try adding `simple_cubic_8.json` to the list of test structures here: https://github.com/cosmo-epfl/librascal/blob/c9523a8f7b14e0a3cd588ed459e81ece4340487d/tests/test_calculator.hh#L420-L426 (thanks @agoscinski for reporting).

I'm not sure yet why we didn't see errors before, and why this structure with this cutoff triggers the error, but I think we should be able to solve it by excluding periodic images of the center from the neighbour iterations here: https://github.com/cosmo-epfl/librascal/blob/c9523a8f7b14e0a3cd588ed459e81ece4340487d/src/rascal/representations/calculator_spherical_invariants.hh#L527
and here: https://github.com/cosmo-epfl/librascal/blob/c9523a8f7b14e0a3cd588ed459e81ece4340487d/src/rascal/representations/calculator_spherical_invariants.hh#L683

and probably also in the corresponding places in the RadialSpectrum implementation.

**Comment by agoscinski** [comment]
Also issue with `simple_cubic_3.json` pbc true with `cutoff=1.0` might be related to this one. This gives a eigen size error, at a different spot in the code.

**Comment by agoscinski** [comment]
The problem arises when the `BlockSparseProperty` got a matrix of size (0,0) as input. Later this zero matrix gets accessed. We could add an assert to the `BlockSparseProperty` to prevent that this behaviour can happen. This could catch bugs earlier ton.

**Comment by max-veit** [comment]
The previous issue (with the structure with `cutoff=1.0`, which just happens to make a neighbour lay right on the cutoff boundary) is probably an effect of #186 -- maybe we need to start thinking about actually fixing it, or at least emitting a warning when the number of neighbours changes from one call to the next.

**Comment by mastricker** [comment]
@max-veit yes that is exactly true. But how would you go about fixing this again with tolerances? Checking tolerances of all distances in a neighbourhood?

So you can not expect an unambiguous neighbour list from a case like this.

**Comment by max-veit** [comment]
For this particular case, let's consider the parable of the doctor who had a patient say, "My arm hurts when I move it like this." The doctor says: "Then don't move it like that."

Basically, for this finite-difference gradient test, we are free to choose the structures and cutoffs at which they are tested, and it's still quite easy to find a cutoff that doesn't break the test for _any_ of the structures.  There are many more cutoffs that don't break the gradient test than cutoffs that do.

We just need to do a slightly better job of warning people who might add structures to the gradient test that you can't have any pairs separated by the cutoff exactly, and report in clear language when this happens so they know what to do.

**Comment by mastricker** [comment]
I agree. I am just saying that the problem can not be solved, regardless of a cutoff + tolerance. There will be another cutoff, like you stated, which is not caught by the tolerance.

So, I agree with your suggestion for a warning. But I am actually not clear on how to implement that other than putting it into the documentation.

I see two cases:
1. The underlying structure does change (if ever so slightly, e.g. from a trajectory) or the cutoff changes. So the neighbourlist can change but must not. This is impossible to catch from the viewpoint of the neighbourlist.
2. The underlying structure does not change and the cutoff does not change, the neighbourlist should not be rebuild based on the rationale that Felix has introduced with the skin (WIP). Ergo, no problem.

So for my understanding: you are only referring to adding structures in the tests or also for production?
I'm sorry, I do not get the _second call_ and change of the number of neighbour.

**Comment by max-veit** [comment]
First off, it is certainly possible to solve #186, even rigorously, but such a solution would take time and effort well out of proportion to the actual impact of this issue -- again, it only affects the gradient test; we won't be using finite-difference in any actual production runs (at least, we don't plan to support it as a way of computing the gradient). This really only pops up when someone (almost certainly a developer) tries to add a structure to the testing list.

So the warning that @felixmusil put into the PR that solved this issue is perfect -- it works, it didn't take too much time to implement, and it effectively warns developers to avoid causing the condition in the first place.

> I'm sorry, I do not get the _second call_ and change of the number of neighbour.

Have you tested with `simple_cubic_3.json` and a cutoff of 1.0? That's a very simple way to trigger this condition, as that structure has two atoms separated by exactly that distance.
