### ISSUE TITLE
Valgrind tutorial

### ISSUE THREAD

**Issue by felixmusil** [cosmo-epfl/librascal#23]
Explain how 
- [ ] Valgrind works  
- [ ] why it is important

**Comment by max-veit** [comment]
Is this meant to be part of the documentation later, or is it just something we expect all developers should know how to use?

**Comment by tjunge** [comment]
Mhm, good question. I never thought about making it part of the doc, but it's true that it might be useful.

What's your preference? How about making this a group decision on the next meeting?

**Comment by mastricker** [comment]
I'll put it up on the list.
I think it can be something in the documentation:
**Before the Pull request**:
- check your code with valgrind, e.g. like this:
....

**Comment by max-veit** [comment]
#63

**Comment by Luthaf** [comment]
Notes for myself: there should be a short tutorial on how to run valgrind for a given test (using ctest built in support: https://stackoverflow.com/a/40437731/3041318)

Then the tests should also be enabled in CI, again using ctest built-in support.

**Comment by max-veit** [comment]
> I think it can be something in the documentation:
> **Before the Pull request**:
> 
>     * check your code with valgrind, e.g. like this:
>       ....

As soon as this is done, I'll add it to our brand new :sparkles: pull request template :sparkles: !
