### ISSUE TITLE
SOAP_CSD500.ipynb is not a proper json anymore

### ISSUE THREAD

**Issue by felixmusil** [cosmo-epfl/librascal#234]
I tried to open this notebook in master (6ffe9dadee70171176441a616c0ad4b3822b8fa2) and it raised an error.

**Comment by koerper** [comment]
The same occurs for me. The error raised is
`Unreadable Notebook: ../librascal/examples/SOAP_CSD500.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "m...',)`

**Comment by max-veit** [comment]
Ok, given that the notebook hasn't been kept up to date with the latest changes in librascal, and that most of its content has been reproduced in `SOAP_example.ipynb`, I'd say it's safe to delete it. We can always access it from the git history if we ever need it again.
