### ISSUE TITLE
Rename ShiftedCosine to CosineShifted (esp. ref data generation scripts)

### ISSUE THREAD

**Issue by mastricker** [cosmo-epfl/librascal#238]
Is done in tests and code, but has to be done in the scripts for reference data.

I am lost with this - the file with the DFT smiles is missing....

Please help me sorting dated/outdated stuff. @max-veit  or @felixmusil ?

**Comment by max-veit** [comment]
Why? What was wrong with the old name? I wouldn't change it, especially if it involves regenerating all the reference data files in their entirety (which is currently necessary with the binary format).

**Comment by mastricker** [comment]
I just do not like the name and I think readability benefits

by
```
Cosine
CosineShifted
```

instead of
```
Cosine
ShiftedCosine
```

My suggestion visually lists it as an option/extension of cosine instead of being separate.

It was intended as a minor change while cleaning up, which apparently led to some other cleanup tasks in #239 because of other changes with reference files, etc.
