### ISSUE TITLE
Will there be an example of how to use the "alchemical" kernel with SOAP?

### ISSUE THREAD

**Issue by wushanyun64** [cosmo-epfl/librascal#242]
Hi,
I'm interested in using the "alchemical" kernel to reduce the dimensionality of the SOAP vector, will there be any examples about this?

**Comment by mastricker** [comment]
Hi,

Sorry for the late reply. First of all, thank you very much for you interest in our library! We are currently in a developing state and adding functionality and usage examples as we go along. Different SOAP kernels will definitely be part of the library in the near future, but it is not there yet, especially not a user-friendly example. Sorry for that.

I suggest you keep checking back in this repository and/or sign up for updates of it so you get notified automatically about changes and future releases.

Thanks,
Markus

**Comment by max-veit** [comment]
One small thing to add: The alchemical kernel doesn't really reduce the dimensionality of the SOAP vector, but rather allows for mixing between different species-(pair-)components of the SOAP vector (aka power spectrum) in the final kernel. This sort of alchemical mixing could be implemented right now in Python by someone reasonably familiar with the C++ code, but we certainly plan to add a more automatic, efficient, and user-friendly way to do this when we implement the full kernel functionality, so stay tuned.

On the other hand, if you're looking to reduce the dimensionality of the SOAP vector, perhaps you're referring to something we call "feature sparsification"? I suggest you check out the paper by [Imbalzano et. al. (J Chem Phys, 2018)](https://aip.scitation.org/doi/full/10.1063/1.5024611) for details.

Hope this helps!
Max

**Comment by wushanyun64** [comment]
Thank you all for your help! 

I'm now looking around trying to find the details on the implementation of this alchemical kernel, if anyone knows the path to such information, that would be a huge help to me. 

Also, Looking forward to your guys' work!
