### ISSUE TITLE
Move `/rascal/*cc-*hh` files to `rascal/utils/`

### ISSUE THREAD

**Issue by mastricker** [cosmo-epfl/librascal#243]
I just noticed that we are becoming slightly inconsistent with file placement.
E.g. our rascal folder contains `utils.hh` and `utils.cc`, which have a better place in the actual folder `/utils/`. And when doing that, we could also go as far as moving everything from there including
```
atomic_structure.hh
basic_types.hh
json_io.cc
json_io.hh
lattice.hh
units.cc
units.hh
utils.cc
utils.hh
```
To the `rascal/utils/` folder.

Any objections with this suggestion?

**Comment by Luthaf** [comment]
atomic_structure and lattice might be better of in structure_managers?

**Comment by mastricker** [comment]
I agree. Any other comments/suggestions/objections?
