### ISSUE TITLE
scalar soap representation

### ISSUE THREAD

**Issue by felixmusil** [cosmo-epfl/librascal#26]
- [x] figure out real spherical harmonics expression
- [x] implement spherical harmonics
- [x] Implement the horrible analytical integral
- [ ] numerical integration functionality for testing
- [ ] RepresentationManager that computes SOAP from the expansion coefficients
- [ ] Different radial basis types
- [x] get direction vectors from the strict manager
- [x] make soap with 1 specie
- [ ] make multi species soap

**Comment by max-veit** [comment]
Closing because most of this has been split off to other issues.
