### ISSUE TITLE
CURFilter does not work for selecting zero or all of a given species

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#272]
Both of the following examples:
```python
n_sparse = {1: 50, 6: 50, 7: 39, 8: 49, 16: 0}
compressor = CURFilter(scalar_rep, n_sparse, act_on='sample per species')
sparse_points_cur = compressor.fit_transform(mols_scalar_soaps)
```

and
```python
n_sparse = {1: 50, 6: 50, 7: 39, 8: 49, 16: 3}
compressor = CURFilter(scalar_rep, n_sparse, act_on='sample per species')
sparse_points_cur = compressor.fit_transform(mols_scalar_soaps)
```

throw the same error:

```
Selecting species: 16

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-01263d19b619> in <module>
      1 n_sparse = {1: 50, 6: 50, 7: 39, 8: 49, 16: 3}
      2 compressor = CURFilter(scalar_rep, n_sparse, act_on='sample per species')
----> 3 sparse_points_cur = compressor.fit_transform(mols_scalar_soaps)

~/Work/librascal/build/rascal/utils/cur.py in fit_transform(self, managers)
    124             for sp in sps:
    125                 print('Selecting species: {}'.format(sp))
--> 126                 selected_ids_by_sp[sp] = np.sort(do_CUR(X_by_sp[sp], self.Nselect[sp], self.act_on,
    127                                                         self.is_deterministic, self.seed))
    128 

~/Work/librascal/build/rascal/utils/cur.py in do_CUR(X, Nsel, act_on, is_deterministic, seed, verbose)
     14     697–702. https://doi.org/10.1073/pnas.0803205106
     15     """
---> 16     U, _, VT = svds(X, Nsel)
     17     if 'sample' in act_on:
     18         weights = np.mean(np.square(U), axis=1)

~/python-envs/atomic/lib/python3.8/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in svds(A, k, ncv, tol, which, v0, maxiter, return_singular_vectors, solver)
   1815 
   1816     if k <= 0 or k >= min(n, m):
-> 1817         raise ValueError("k must be between 1 and min(A.shape), k=%d" % k)
   1818 
   1819     if isinstance(A, LinearOperator):

ValueError: k must be between 1 and min(A.shape), k=3
```

The structures and representations are the same as for #268 and contain the following numbers of centres of each species:
```
416 centres of species Z=1
246 centres of species Z=6
40 centres of species Z=7
50 centres of species Z=8
3 centres of species Z=16
```

My guess is that this is a limitation of the underlying SVD linear algebra routine, so these two cases (which will be quite common in practice; there are many scenarios in which one would like to select all atoms of a given species as sparse points, especially if they are underrepresented in the dataset) will need to be treated specially.

**Comment by felixmusil** [comment]
Your guess is on point, the SVD routine does not handle these two cases. It is also quite simple to handle these 2 cases separately I think even though I am not sure about the usefulness of having 0 sparse points for a particular central atom species. Could you expand on that further ?

**Comment by max-veit** [comment]
If anything for symmetry, but perhaps also to be able to "mask out" a given species from the sparse set; maybe it would be useful if someone wants to study the effect of completely eliminating a given central atom type from the sparse set.

**Comment by max-veit** [comment]
I think the error actually goes deeper than this. When running CUR on a very "tall" matrix (many rows, few columns), the error recurs:
```python
The number of pseudo points selected by central atom species is: {8: 100, 22: 100, 56: 100}
Selecting species: 8

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-27-a2245884a746> in <module>
      1 n_sparse = {8: 100, 22: 100, 56: 100}
      2 compressor = CURFilter(rep_2b, n_sparse, act_on='sample per species')
----> 3 sparse_points_cur = compressor.fit_transform(soaps_2b)
      4 dump_obj('rascaltest/sparsepoints_2b.json', sparse_points_cur)

/local/scratch/mveit/miniconda3/envs/rascal-clean/lib/python3.7/site-packages/rascal-0.0.0-py3.7-linux-x86_64.egg/rascal/utils/cur.py in fit_transform(self, managers)
    125                 print('Selecting species: {}'.format(sp))
    126                 selected_ids_by_sp[sp] = np.sort(do_CUR(X_by_sp[sp], self.Nselect[sp], self.act_on,
--> 127                                                         self.is_deterministic, self.seed))
    128 
    129             self.selected_ids = self.convert_selected_global_index2rascal_sample_per_species(

/local/scratch/mveit/miniconda3/envs/rascal-clean/lib/python3.7/site-packages/rascal-0.0.0-py3.7-linux-x86_64.egg/rascal/utils/cur.py in do_CUR(X, Nsel, act_on, is_deterministic, seed, verbose)
     14     697–702. https://doi.org/10.1073/pnas.0803205106
     15     """
---> 16     U, _, VT = svds(X, Nsel)
     17     if 'sample' in act_on:
     18         weights = np.mean(np.square(U), axis=1)

~/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in svds(A, k, ncv, tol, which, v0, maxiter, return_singular_vectors)
   1784 
   1785     if k <= 0 or k >= min(n, m):
-> 1786         raise ValueError("k must be between 1 and min(A.shape), k=%d" % k)
   1787 
   1788     if isinstance(A, LinearOperator):

ValueError: k must be between 1 and min(A.shape), k=100

> /home/veit/.local/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py(1786)svds()
   1784 
   1785     if k <= 0 or k >= min(n, m):
-> 1786         raise ValueError("k must be between 1 and min(A.shape), k=%d" % k)
   1787 
   1788     if isinstance(A, LinearOperator):

ipdb> A.shape
(12432, 18)
```
But I should be able to do a CUR on the environments (rows) regardless of the dimension of the features (columns) - so in this case I think the use of the sparse SVD is wrong, since it doesn't allow to do an (exact, full) SVD that this case requires. In fact, I doubt the sparse SVD is really necessary in any case, since it's explicitly designed to be used for sparse matrices -- the only advantage it has is that you can compute a subset of all the singular values which probably saves some computational cost.

So: (1) would you be OK with replacing the sparse SVD with the full SVD in the limit of `Nsel` approaching the minimum dimension of the feature matrix?

and (2) have you tested sparse vs. full SVD in the case where `Nsel` is much smaller than either dimension of the feature matrix? From what I can tell from the docs, the only difference with `scipy.sparse.linalg.svds` is that it uses a sparse iterative algorithm to get the first few eigenvalues in an approximate fashion; I suppose that could be more efficient in the case where both matrix dimensions are _much_ larger than the number of samples requested.

**Comment by felixmusil** [comment]
You are right this limitation is too troublesome. Do you mind taking care of putting a switch where the sparse svd would be used when possible and else full svd ? Also you could put a test to see if `Nsel==N` or `Nsel==0` ?

**Comment by max-veit** [comment]
I'm guessing this is fixed by the replacement of `CURFilter` with the `scikit-cosmo` version in #347
