### ISSUE TITLE
Better Tests

### ISSUE THREAD

**Issue by felixmusil** [cosmo-epfl/librascal#28]
- [x] add test for very skewed cell, like Michele suggested to test the robustness of the algorithm

- [ ] Refactor the tests to streamline them (use template fixtures to test common functionalities)

- [ ] Comment the variable that come from the fixture

- [ ] test_adaptor_strict.cc still has the description of the neighbour list builder.

- [ ] Make code snippets in the tests to be used in the documentation for the tutorials

- [ ] Make more/systematically examples that highlight the functionalities of the code
- [x]  Template test for basic interface of all structure managers

- [ ] Add test for 2 dimensional structures

- [x] Remove manager chain and change it's usage in alanine_chain.cc example to StructureManagerCenters

- [ ] Add AdaptorFilter to the `fixtures` list in `test_structure_manager_interface.cc`

**Comment by max-veit** [comment]
The pull request with the same name has been closed, so I'm closing the issue. Any further points from above should be moved to more specific issues.

**Comment by mastricker** [comment]
Moved the undone things of the list to a different note.
Decision was done to not fill up the PR again with too many different things.
