### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by sandipde** [cosmo-epfl/librascal#287]
Hi, I was trying to install the library and hit several bumps ! 
Simple one: please include Scikit-build library in the requirement list. This is the first library it needs but it is not mentioned in the dependencies.
A not so simple one: pip install . failed for me. A bit investigation by trying to build manually with cmake ../  revealed that the problem arises because the automatic download attempt from http://fy.chalmers.se/subatom/wigxjpf/wigxjpf-1.9.tar.gz fails for our supercomputer. This is unavoidable because of our firewall rules. I tried via downloading the file myself and putting it in the same location and rerunning the cmake  but the code tries to download again and fails. How do I go around it ?  
Thanks in advance. 

cmake ..
-- Build type is: Release
-- The CXX compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /software/app/gnu/gcc/8.2.0/bin/g++
-- Check for working CXX compiler: /software/app/gnu/gcc/8.2.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Downloading wigxjpf
CMake Error at cmake/rascalTools.cmake:170 (message):
  Something went wrong (2) during the download process of wigxjpf check the
  file
  /gpfs/nobackup/sandip/venv/librascal/build/third-party/wigxjpf-download/build-error.log
  for more details
Call Stack (most recent call first):
  cmake/wigxjpf.cmake:5 (download_external_project)
  cmake/rascalTools.cmake:225 (include)
  CMakeLists.txt:115 (add_external_package)

-- Configuring incomplete, errors occurred!

**Comment by felixmusil** [comment]
Thanks for reporting this issue. 

(1) I am a bit surprised by this problem since it is part of the build dependencies (see pyptoject.toml and [pep518](https://www.python.org/dev/peps/pep-0518/) specifications) and it should be installed temporarily if not already available. Maybe your `pip` version is too old ? 

(2) The simplest workaround that I can think of is:
+ get a copy of wigxjpf-1.9.tar.gz on your machine
+ modify `cmake/wigxjpf.cmake` line 6 to `URL "file:///<path to file>"` where `<path to file>` is the path to wigxjpf-1.9.tar.gz
Then `pip install .` should work fine.

**Comment by sandipde** [comment]
Hi @felixmusil Thanks for your quick reply. 
(1) Might be. Just adding the scikit-build in the top of requirement.txt would solve this easily though. 
(2) Yur suggestion worked ! But now it fails to compile 


[  3%] Building CXX object src/CMakeFiles/rascal.dir/rascal/utils/json_io.cc.o
In file included from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp: In static member function ‘static void nlohmann::detail::lexer<BasicJsonType>::strtof(float&, const char*, char**)’:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:7954:18: error: ‘strtof’ is not a member of ‘std’
         f = std::strtof(str, endptr);
                  ^~~~~~
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:7954:18: note: suggested alternative: ‘sqrt’
         f = std::strtof(str, endptr);
                  ^~~~~~
                  sqrt
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp: In static member function ‘static void nlohmann::detail::lexer<BasicJsonType>::strtof(long double&, const char*, char**)’:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:7966:18: error: ‘strtold’ is not a member of ‘std’
         f = std::strtold(str, endptr);
                  ^~~~~~~
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:7966:18: note: suggested alternative:
In file included from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/cstdlib:75,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/bits/stl_algo.h:59,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/algorithm:62,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:37,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/usr/include/stdlib.h:175:20: note:   ‘strtold’
 extern long double strtold (const char *__restrict __nptr,
                    ^~~~~~~
In file included from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp: In member function ‘nlohmann::detail::lexer<BasicJsonType>::token_type nlohmann::detail::lexer<BasicJsonType>::scan_number()’:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:8293:33: error: ‘strtoull’ is not a member of ‘std’
             const auto x = std::strtoull(token_buffer.data(), &endptr, 10);
                                 ^~~~~~~~
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:8293:33: note: suggested alternative:
In file included from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/cstdlib:75,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/bits/stl_algo.h:59,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/algorithm:62,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:37,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/usr/include/stdlib.h:214:31: note:   ‘strtoull’
 extern unsigned long long int strtoull (const char *__restrict __nptr,
                               ^~~~~~~~
In file included from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:8309:33: error: ‘strtoll’ is not a member of ‘std’
             const auto x = std::strtoll(token_buffer.data(), &endptr, 10);
                                 ^~~~~~~
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:8309:33: note: suggested alternative:
In file included from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/cstdlib:75,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/bits/stl_algo.h:59,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/algorithm:62,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:37,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/usr/include/stdlib.h:209:22: note:   ‘strtoll’
 extern long long int strtoll (const char *__restrict __nptr,
                      ^~~~~~~
In file included from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp: In member function ‘bool nlohmann::detail::parser<BasicJsonType>::sax_parse_internal(SAX*)’:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:8912:59: error: expected unqualified-id before ‘(’ token
                         if (JSON_HEDLEY_UNLIKELY(not std::isfinite(res)))
                                                           ^~~~~~~~
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:1118:58: note: in definition of macro ‘JSON_HEDLEY_UNLIKELY’
 #  define JSON_HEDLEY_UNLIKELY(expr) __builtin_expect(!!(expr), 0)
                                                          ^~~~
In file included from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp: In static member function ‘static int nlohmann::json_pointer<BasicJsonType>::array_index(const string&)’:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:10407:35: error: invalid initialization of reference of type ‘const wstring&’ {aka ‘const std::__cxx11::basic_string<wchar_t>&’} from expression of type ‘const string’ {aka ‘const std::__cxx11::basic_string<char>’}
         const int res = std::stoi(s, &processed_chars);
                                   ^
In file included from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/string:52,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/stdexcept:39,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/array:39,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/tuple:39,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/functional:54,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:41,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/software/app/gnu/gcc/8.2.0/include/c++/8.2.0/bits/basic_string.h:6507:3: note: in passing argument 1 of ‘int std::__cxx11::stoi(const wstring&, std::size_t*, int)’
   stoi(const wstring& __str, size_t* __idx = 0, int __base = 10)
   ^~~~
In file included from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/cmath:45,
                 from /software/app/gnu/gcc/8.2.0/include/c++/8.2.0/valarray:37,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:70,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:44,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp: In function ‘char* nlohmann::detail::to_chars(char*, const char*, FloatType)’:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:13715:14: error: expected unqualified-id before ‘(’ token
     if (std::signbit(value))
              ^~~~~~~
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp: In member function ‘void nlohmann::detail::serializer<BasicJsonType>::dump_float(nlohmann::detail::serializer<BasicJsonType>::number_float_t)’:
/gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/external/json.hpp:14431:22: error: expected unqualified-id before ‘(’ token
         if (not std::isfinite(x))
                      ^~~~~~~~
In file included from /gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/Core:371,
                 from /gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/Dense:1,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.hh:48,
                 from /gpfs/nobackup/projects/softmatter/sandip/venv/librascal/src/rascal/utils/json_io.cc:28:
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h: In static member function ‘static Scalar Eigen::internal::round_impl<Scalar>::run(const Scalar&)’:
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h:392:18: error: ‘std::round’ has not been declared
       using std::round;
                  ^~~~~
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h: In static member function ‘static Scalar Eigen::internal::log1p_impl<Scalar>::run(const Scalar&)’:
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h:484:16: error: ‘std::log1p’ has not been declared
     using std::log1p;
                ^~~~~
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h: In function ‘typename Eigen::internal::enable_if<((! Eigen::internal::is_integral<T>::value) && (! Eigen::NumTraits<T>::IsComplex)), bool>::type Eigen::internal::isfinite_impl(const T&)’:
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h:712:16: error: ‘std::isfinite’ has not been declared
     using std::isfinite;
                ^~~~~~~~
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h: In function ‘typename Eigen::internal::enable_if<((! Eigen::internal::is_integral<T>::value) && (! Eigen::NumTraits<T>::IsComplex)), bool>::type Eigen::internal::isinf_impl(const T&)’:
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h:727:16: error: ‘std::isinf’ has not been declared
     using std::isinf;
                ^~~~~
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h: In function ‘typename Eigen::internal::enable_if<((! Eigen::internal::is_integral<T>::value) && (! Eigen::NumTraits<T>::IsComplex)), bool>::type Eigen::internal::isnan_impl(const T&)’:
/gpfs/backup/users/home/desa/.local/include/eigen3/Eigen/src/Core/MathFunctions.h:742:16: error: ‘std::isnan’ has not been declared
     using std::isnan;
                ^~~~~
make[2]: *** [src/CMakeFiles/rascal.dir/rascal/utils/json_io.cc.o] Error 1
make[1]: *** [src/CMakeFiles/rascal.dir/all] Error 2
make: *** [all] Error 2

**Comment by felixmusil** [comment]
Which compiler and which version are you using ? Seems like it is not c++14 compatible.

**Comment by sandipde** [comment]
Hi Felix,
    Our server is closed for maintenance for next 2 days. I shall get back
after that. May be I missed to load a correct module in our supercomputer.
Thanks

**Comment by sandipde** [comment]
Turns out that gcc8.2.0 compiler I was using was the problem, It worked smothly with gcc/7.2.0 worked smoothly
