### ISSUE TITLE
read the docs integration

### ISSUE THREAD

**Issue by felixmusil** [cosmo-epfl/librascal#30]

**Comment by rosecers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Work on read the docs implementation for lib_rascal documentation](https://trello.com/c/uRTWXYti/7-work-on-read-the-docs-implementation-for-librascal-documentation)

**Comment by max-veit** [comment]
@Luthaf assigning you because you mentioned it might be possible to do an automatic build on gh-pages?

**Comment by Luthaf** [comment]
I'll look into this on Monday ! I have a working version with Travis CI (http://chemfiles.org/chemfiles/), I just need to adapt it to Circle CI

**Comment by Luthaf** [comment]
This is done, documentation is now online and auto updated at https://cosmo-epfl.github.io/librascal/index.html
