### ISSUE TITLE
Dictionary returned by `to_dict` is not serializable to JSON

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/librascal#306]
I would expect this code to work:

```py
from rascal.models import train_gap_model
model = train_gap_model(
    # ...
)

json.dump(to_dict(model), open("model.json", "w"))
```

But I get the following error:
```
Traceback (most recent call last):
  File "train_gap.py", line 114, in <module>
    json.dump(to_dict(model), open("model.json", "w"))
  File "/opt/miniconda3/lib/python3.7/json/__init__.py", line 179, in dump
    for chunk in iterable:
  File "/opt/miniconda3/lib/python3.7/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/miniconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/opt/miniconda3/lib/python3.7/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/opt/miniconda3/lib/python3.7/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/opt/miniconda3/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```

**Comment by felixmusil** [comment]
The dictionary representation of the object returned by `to_dict` is not JSON serializable like many dictionaries so it is expected to fail. Please use `to_file` function to save a model.

**Comment by Luthaf** [comment]
I ended up using pickle, which worked fine. What is the rational to have both `to_dict` and `to_file` here?

**Comment by felixmusil** [comment]
Large numpy arrays are saved separately so that they can be loaded efficiently or memory mapped.

**Comment by max-veit** [comment]
Also, pickle isn't human-readable, whereas json is. But how does the code decide whether to save an array separately versus include it directly in the json? For instance, all of the models I've trained so far keep the weights and sparsepoints arrays inside the json (making for a huge file, btw), rather than saving them separately.

**Comment by felixmusil** [comment]
There is a threshold on the size which is 60MB if I recall well. I had kernel matrices in mind mostly, maybe it should be lowered ?
