### ISSUE TITLE
get_gradients_info is missing data

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/librascal#326]
Using a frame containing 8 atoms, the following code 

```py
soap = SphericalInvariants(**SOAP_HYPERS)
managers = soap.transform(frames)

print("features", managers.get_features(soap).shape)
print("gradients", managers.get_features_gradient(soap).shape)

print("get_representation_info", managers.get_representation_info().shape)
print("get_gradients_info", managers.get_gradients_info().shape)
```

Gives the following output:

```
features (8, 1512)
gradients (144, 1512)
get_representation_info (8, 3)
get_gradients_info (48, 5)
```

While the gradient array contains 144 rows, the associated metadata from "get_gradients_info" only contains 48 rows.

@felixmusil since you introduced these functions in #317 do you know what is going on here?

EDIT: here is a full reproduction: you can run `tmp.py` with the latest master of librascal. 
[missing-grad-meta.zip](https://github.com/cosmo-epfl/librascal/files/6197594/missing-grad-meta.zip)

**Comment by felixmusil** [comment]
As mentioned in the docstring of `get_features_gradient` the size of the returned array is expected to be 3*(n_atoms+n_neighbors) so this is an expected behavior.

**Comment by Luthaf** [comment]
Right, my bad ...

144 is (3 x 48), so each row in `get_gradients_info` corresponds to three row in `get_features_gradient`, one for each of x/y/z.

Sorry about this!
