### ISSUE TITLE
Add automatic notebook validation to tests

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#339]
This is part of our effort to expand the automated test suite to catch errors that users are likely to run into upon first running the code -- one of which being errors in the example notebooks, which are not currently checked. However, there are tools available for us to check these automatically in case we forget to run them (or in case they contain system-dependent parameters); thanks @rosecers for alerting me to these! In particular, it seems [`nbval`](https://pypi.org/project/nbval/)  (a pytest plugin) would work very well for our particular situation, see e.g. [this file](https://github.com/cosmo-epfl/kernel-tutorials/blob/master/.github/workflows/synced.yml) for an example of how this can be done. (yes, I know it's written for github workflows, but porting it to CircleCI would be almost trivial).

**Comment by boyuan12** [comment]
Can I try to work on this issue?

**Comment by max-veit** [comment]
Hi Boyuan, thanks for your interest! I think this might not actually be a good issue to start with, however, since it's entangled with the organization of our existing examples and a few other issues we're working on in the background - and anyway I'm already working on it as part of PR #342.

Might I suggest instead that you have a look at an issue like #332, #333, or #330 ? I think these would be better "first issues" than this one. I'll be happy to provide any information you need to work on one of those issues.
