### ISSUE TITLE
Specify positions where to calculate SOAP

### ISSUE THREAD

**Issue by tsitsvero** [cosmo-epfl/librascal#360]
In lib DScribe I can specify points at which calculate representation by `positions` argument.

E.g. the following will calculate representations only around atoms 1,2 and 3
```
soap.create(frame, positions=[1,2,3]))
```

Is there a way to specify positions at which calculate representations in librascal? 

I can't find option for `soap.transform(frames_train)`, maybe I'm missing something.

**Comment by agoscinski** [comment]
Yes you can mask atoms, so the representation is only computed for the selected ones
```python
from rascal.neighbourlist.structure_manager import mask_center_atoms_by_id 
mask_center_atoms_by_id(frame, id_select=[1,2,3])
```
you can also use `id_blacklist` instead, if you want to only mention the atoms which should not be computed
you can also mask by species with `mask_center_atoms_by_species`
It just sets another entry `center_atoms_mask` in the frame.arrays which is then later checked

**Comment by tsitsvero** [comment]
> Yes you can mask atoms, so the representation is only computed for the selected ones
> 
> ```python
> from rascal.neighbourlist.structure_manager import mask_center_atoms_by_id 
> mask_center_atoms_by_id(frame, id_select=[1,2,3])
> ```
> 
> you can also use `id_blacklist` instead, if you want to only mention the atoms which should not be computed
> you can also mask by species with `mask_center_atoms_by_species`
> It just sets another entry `center_atoms_mask` in the frame.arrays which is then later checked

Cool, thanks!

Equivalently to what you suggested I set mask manually for Atoms object:
```python
frame.arrays["center_atoms_mask"] = [False, False, True, False]
```
