### ISSUE TITLE
Zundel notebook fails to run on CircleCI

### ISSUE THREAD

**Issue by Luthaf** [cosmo-epfl/librascal#382]
This fails the corresponding builder. See one example here: https://app.circleci.com/pipelines/github/cosmo-epfl/librascal/2704/workflows/c3842d71-9c6f-4de2-8eaa-2dda95bd6af5/jobs/23781 and some related discussion there: https://github.com/cosmo-epfl/librascal/pull/381#issuecomment-918316034

**Comment by max-veit** [comment]
This is fixed by #395
