### ISSUE TITLE
structure manager factory

### ISSUE THREAD

**Issue by felixmusil** [cosmo-epfl/librascal#44]
- [ ] shared pointer instead of reference in the structure managers

- [ ] additional constructor taking arguments as a tuple and unpack calling the main constructor

**Comment by tjunge** [comment]
Hi Félix,
What is your motivation? Is it for memory safety? The downside would be that It will no longer allow us to create Managers on the stack, which I find useful.

**Comment by felixmusil** [comment]
while making the tests I realized that the user need to take care of keeping alive all the managers otherwise you end up in seg fault. Having the smart_pointer instead of a reference would alleviate this duty from the user.
Do you think that it is not worth it ?

**Comment by felixmusil** [comment]
Let's do it for the sake of simplifying the bindings, utility functions, factories class...

**Comment by felixmusil** [comment]
this has been implemented a while ago
