### ISSUE TITLE
Update license boilerplate comment

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#46]
The licensing comment at the beginning of each C++ file currently reads:
```cpp
/**
 * [...]
 * You should have received a copy of the GNU General Public License            
 * along with GNU Emacs; see the file COPYING. If not, write to the             
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,                 
 * Boston, MA 02111-1307, USA.                                                  
 */  
```
but this isn't GNU Emacs and we don't have a file named `COPYING` -- and, more importantly, we're using LGPL (not GPL), so I suggest we update it to the following:
```cpp
/**
 * [...]
 * You should have received a copy of the GNU Lesser General Public License            
 * along with this software; see the file LICENSE. If not, write to the             
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,                 
 * Boston, MA 02111-1307, USA.                                                  
 */  
```
It's a simple bulk search/replace, but it'll affect all files and has the potential to cause a lot of nasty merge conflicts. I suppose we should do this in the master branch and encourage everyone to pull ASAP.

**Comment by mastricker** [comment]
Thanks, thats a good catch. I see the problem about the COPYING file, fully agree.

But: We have agreed on the GNU GPL. Not the LGPL.
Or did I miss something?

**Comment by ceriottm** [comment]
We had some discussion, but didn't really agree on something. We're meeting
tomorrow morning, right? Let's discuss tomorrow.
I'm inclined to "same as AiiDA", which would be LGPL.
Michele
