### ISSUE TITLE
CircleCI: compiler versions

### ISSUE THREAD

**Issue by mastricker** [cosmo-epfl/librascal#58]
Just to put it somewhere, because I noticed and it is also in the meeting notes:

gcc compiler versions, please change compilers to
gcc 5.4 (because default on Ubuntu 16.04)
(maybe gcc 6.4 (because default on fidis), but not necessary)
gcc 7.3 (because default on Ubuntu 18.04 and available on fidis and relatively recent)

clang compiler, 
clang 3.8 (because default on Ubuntu 16.04 and supports c++14)
clang 6.0 (because default on Ubuntu 18.04)

Any later, newer versions also welcome, but I think those should at least be included in the CI.

Just for reference: I am developing with gcc 8.2 and clang 6.0.1.

Any comments/objections to the proposed version change?

**Comment by gibertif** [comment]
Hello and thanks for the memo!

I have no issues in implementing these too.
