### ISSUE TITLE
Add the possibility to change how the IncreaseMaxOrder is done

### ISSUE THREAD

**Issue by felixmusil** [cosmo-epfl/librascal#59]
add to increase max level adaptor a template parameter to choose between different definitions of the neighborhood in the next order.
Examples of next order neighborhoods: 
+ the neighbors of the current order
+ the union of the neighbors of the current and previous order
+ the intersection of the neighbors of the current and previous order

**Comment by ceriottm** [comment]
Duplicate of #31
