### ISSUE TITLE
Error importing from librascal.so

### ISSUE THREAD

**Issue by sgay** [cosmo-epfl/librascal#66]
Hi Everyone,

I've created this as an issue here so as not to clog up the slack. Michele has successfully got the fps working and I am using a his python script but have an import issue.

When running his [script](https://github.com/cosmo-epfl/librascal/blob/feat/fps_redux/tests/test_sparsify_fps.py) I insert the rascal build directory into my sys.path successfully.

The next line is
> from rascal.utils import fps

Which starts a series of imports in the build directory.  The traceback shows
  ```
  File "/local/projects/librascal/tests/test_sparsify_fps.py", line 6, in <module>
    from rascal.utils import fps #, fps_voronoi
  File "/local/projects/librascal/build/rascal/__init__.py", line 1, in <module>
    from . import lib, representation, utils
  File "/local/projects/librascal/build/rascal/lib/__init__.py", line 1, in <module>
    from rascal.utils import (StructureManager,FeatureManager,Adaptor,
  File "/local/projects/librascal/build/rascal/utils/__init__.py", line 1, in <module>
    from .structure_manager import (ase2rascal,get_strict_neighbourlist)
  File "/local/projects/librascal/build/rascal/utils/structure_manager.py", line 3, in <module>
    from ..lib.librascal import StructureManager,Adaptor
ImportError: cannot import name 'StructureManager' from 'rascal.lib' (/local/projects/librascal/build/rascal/lib/__init__.py)
```

From ![this screenshot](https://user-images.githubusercontent.com/45353982/50332454-72773800-0502-11e9-8194-c8899e402c2d.png) you can see that I have `build/rascal/lib/librascal.so` present and it compiled with no issues. The module *is* recognised as removing it causes the error to change to not being able to find the module.

I have tried using a copy of michele's librascal.so, libcephes.so, and librascal-math.so, but not the _rasca.cpython... file as he is running python 3.6 and I'm on 3.7. None of this changes the error.

Can anyone think of a reason for this problem?

**Comment by mastricker** [comment]
One quick thing:
3.6 to 3.7: I have to change it manually in the cmake config to be on 3.6
Forgot what the issues was.

I am working on feat/python_bindings to change the structure

**Comment by sgay** [comment]
Ok so this is the weirdest thing, Michele managed to work it out. For whatever reason, I can only import from within build, absolutely no clue why, looks to be an issue with my python install.

**Comment by ceriottm** [comment]
to be clear (I witnessed and can't understand it) if you copy
test_sparsify_fps.py into build,

....build/$  python3 test_sparsify_fps.py

works fine, but

....build/$  python3 ../tests/test_sparsify_fps.py

raises an error on import rascal.

**Comment by felixmusil** [comment]
My guess is that test_sparsify_fps.py imports _rascal or rascal since at the cmake step it is expected to be copied into the build folder. Then, ../tests/test_sparsify_fps.py does not have rascal in the same folder it does not find it.

Again as things stand, the python tests are copied into the build folder and they expect to be run from there to work.

Is it clearer now ?
