### ISSUE TITLE
Change unit abbreviation for ångströms ("A" ↦ "AA")

### ISSUE THREAD

**Issue by max-veit** [cosmo-epfl/librascal#96]
I guess this got merged into master now, so before it becomes impossible to change: We really shouldn't use the short name "A" for ångströms. For one, it stands for amperes in SI - I know this is an atomic structure code and it's unlikely someone would confuse a length with a current, but it's still wrong and potentially misleading.

As an alternative, rather than making users switch their kezboard layouts or copy-paste "Å" from Wikipedia, we could just use "AA" (as in LaTeX) or "Ang" (also widely recognized and unambiguous). Let's change this before we implement the unit police / input checkers at the very latest.

**Comment by felixmusil** [comment]
I agree with you. Let's use AA.

**Comment by ceriottm** [comment]
We could also use Å. C++11 supports unicode, and if you can't type Å you
deserve to use SI units.
Just kidding, AA will be fine

**Comment by ceriottm** [comment]
Did this get fixed?
